name: Build and Push Docker Images
on:
  push:
    tags:
      - "mealierag*"
env:
  REGISTRY: ghcr.io
  MEALIERAG_IMAGE_NAME: ${{ github.repository_owner }}/mealierag
jobs:
  build-and-push-mealierag:
    name: Build and Push Mealierag
    runs-on: ubuntu-latest
    # Only run for mealierag tags
    if: contains(github.ref, 'mealierag')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push Mealierag Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/mealierag
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.MEALIERAG_IMAGE_NAME }}:${{ steps.tag.outputs.TAG }}
            ${{ env.REGISTRY }}/${{ env.MEALIERAG_IMAGE_NAME }}:latest
    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
      app: mealierag
